const PRODUCT_LOADING = "PRODUCT_LOADING"
const PRODUCT_SUCCESS = "PRODUCT_SUCCESS"
const PRODUCT_ERROR = "PRODUCT_ERROR"
const CURRENT_PRODUCT_LOADING = "CURRENT_PRODUCT_LOADING"
const CURRENT_PRODUCT_SUCCESS = "CURRENT_PROUCT_SUCCESS"
const CURRENT_PRODUCT_ERROR = "CURRENT_PRODUCT_ERROR"

// men product k
const MEN_PRODUCT_LOADING = "MEN_PRODUCT_LOADING"
const MEN_PRODUCT_SUCCESS = "MEN_PRODUCT_SUCCESS "
const MEN_PRODUCT_ERROR = "MEN_PRODUCT_ERROR"


// women product k
const WOMEN_PRODUCT_LOADING = "WOMEN_PRODUCT_LOADING"
const WOMEN_PRODUCT_SUCCESS = "WOMEN_PRODUCT_SUCCESS"
const WOMEN_PRODUCT_ERROR = "WOMEN_PRODUCT_ERROR"




export {PRODUCT_LOADING,PRODUCT_SUCCESS,PRODUCT_ERROR,CURRENT_PRODUCT_LOADING,CURRENT_PRODUCT_SUCCESS,CURRENT_PRODUCT_ERROR,
MEN_PRODUCT_LOADING,MEN_PRODUCT_SUCCESS,MEN_PRODUCT_ERROR,WOMEN_PRODUCT_LOADING,WOMEN_PRODUCT_SUCCESS,WOMEN_PRODUCT_ERROR}