const PRODUCT_LOADING = "PRODUCT_LOADING"
const PRODUCT_SUCCESS = "PRODUCT_SUCCESS"
const PRODUCT_ERROR = "PRODUCT_ERROR"
const CURRENT_PRODUCT_LOADING = "CURRENT_PRODUCT_LOADING"
const CURRENT_PRODUCT_SUCCESS = "CURRENT_PROUCT_SUCCESS"
const CURRENT_PRODUCT_ERROR = "CURRENT_PRODUCT_ERROR"

export {PRODUCT_LOADING,PRODUCT_SUCCESS,PRODUCT_ERROR,CURRENT_PRODUCT_LOADING,CURRENT_PRODUCT_SUCCESS,CURRENT_PRODUCT_ERROR}